print ( " what is a combination car? " )
print ( " a combination car can be used as a hearse and an ambulance " )
print ( " people have asked me what they are all of the time, so, i'm going to answer that question for those people " )
print ( " in Ghostbusters, they use a combination car " )
print ( " the car they used was a 1969 cadillac miller meteor hearse/ambulance " )
print ( " and surprisingly it's still with us " )
print ( " how is that car still with us? " )
